### ISSUE TITLE
Issue with self-hosted WCF

### ISSUE THREAD

**Issue by Alexander1967muc** [Microsoft/ApplicationInsights-SDK-Labs#109]
Hello!

I'm having an issue when using AI.WCF with a self-hosted WCF Service.
In my Service method, I'm using OperationContext.Current.GetRequestTelemetry() to get the current RequestTelemetry object so that I can add custom properties.
If I call the method in short intervals, I getting the same RequestTelemetry object from the previous call instead of a new object. The Service is set to InstanceContextMode.PerCall.
The exact same Service when run as an IIS-hosted WCF-Service does not show this behaviour.

Any ideas?

Thanks
Alexander

**Comment by SergeyKanzhelev** [comment]
@tomasr 

@Alexander1967muc do you have a small repro app?

**Comment by tomasr** [comment]
Any info you can provide on what your code looks like would be useful. The request telemetry object is directly tied to the `OperationContext` object, unless we end up looking for said context in the thread's logical call context, which should not be happening in such a scenario....

**Comment by Alexander1967muc** [comment]
Hi Tomas,

thanks for getting back.

I just responded with a sample app.
I hope the ZIP file goes through.

Cheers
Alexander

Von: Tomas Restrepo [mailto:notifications@github.com]
Gesendet: Donnerstag, 13. April 2017 21:58
An: Microsoft/ApplicationInsights-SDK-Labs <ApplicationInsights-SDK-Labs@noreply.github.com>
Cc: Roethinger, Alexander <aroethinger@affili.net>; Mention <mention@noreply.github.com>
Betreff: Re: [Microsoft/ApplicationInsights-SDK-Labs] Issue with self-hosted WCF (#109)


Any info you can provide on what your code looks like would be useful. The request telemetry object is directly tied to the OperationContext object, unless we end up looking for said context in the thread's logical call context, which should not be happening in such a scenario....

**Comment by Alexander1967muc** [comment]
Hi Sergey,

thanks for getting back to me!
I’ve prepared and attached a small solution that reproduces the behavior.

The solution contains three projects:
* WcfService1 – a standard IIS hosted WcfProject
* WcfServiceLibrary1 – a service library containing the same contract as WcfService1
* WcfServiceLibraryConsoleApplication1 – a console app which hosts WcfServiceLibrary1

The service method returns the current RequestTelemetry.Id.

Steps to reproduce:
1) Load the solution and restore nugget packages
2) Add a valid InstrumentationKey to both ApplicationInsights.config files
3) Start the solution (launches both the WcfService as well as the Console App and starts WcfTestClient)
4) In WcfTestClient, run the RequestID method of the WcfService. You will see that each call returns a new unique Request.Id, even if you subsequently execute the method very quickly
5) Now add a service reference to the self-hosted service (http://localhost:8733/Sample/WcfServiceLibrary1/Service1)
6) Run the RequestID method for the self-hosted service. You will see that the RequestID is not unique per consecutive call, especially if run the method in very short intervals.
Apart from not tracing unique calls, the poses a problem when trying to add custom properties to the collection.

So to me it seems that when self-hosting a WcfService, the Telemetry Session is somehow not being terminated correctly when the call is finished, resulting in subsequent calls using the same Telemetry Session even though each call is unique.
(I did check to ensure that the InstanceContextMode is PerCall)

I hope I’m not doing something totally wrong…. ☹

Let me know if you need any more information.
Thanks again for your support!!

Cheers
Alexander



Von: Sergey Kanzhelev [mailto:notifications@github.com]
Gesendet: Donnerstag, 13. April 2017 05:31
An: Microsoft/ApplicationInsights-SDK-Labs <ApplicationInsights-SDK-Labs@noreply.github.com<mailto:ApplicationInsights-SDK-Labs@noreply.github.com>>
Cc: Roethinger, Alexander <aroethinger@affili.net<mailto:aroethinger@affili.net>>; Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Betreff: Re: [Microsoft/ApplicationInsights-SDK-Labs] Issue with self-hosted WCF (#109)


@tomasr<https://github.com/tomasr>

@Alexander1967muc<https://github.com/Alexander1967muc> do you have a small repro app?

**Comment by tomasr** [comment]
It doesn't seem the attachment is making it though... could you try sending it to tomas @ winterdom.com?

**Comment by Alexander1967muc** [comment]
Done.

Cheers
Alexander

Von: Tomas Restrepo [mailto:notifications@github.com]
Gesendet: Donnerstag, 13. April 2017 22:28
An: Microsoft/ApplicationInsights-SDK-Labs <ApplicationInsights-SDK-Labs@noreply.github.com>
Cc: Roethinger, Alexander <aroethinger@affili.net>; Mention <mention@noreply.github.com>
Betreff: Re: [Microsoft/ApplicationInsights-SDK-Labs] Issue with self-hosted WCF (#109)


It doesn't seem the attachment is making it though... could you try sending it to tomas @ winterdom.com?

**Comment by tomasr** [comment]
@Alexander1967muc Thanks for the repro; just submitted a PR that should fix this issue.

**Comment by Alexander1967muc** [comment]
Wow, thanks!

**Comment by SergeyKanzhelev** [comment]
Fix should be on myget

**Comment by Alexander1967muc** [comment]
Works as expected now.
Thanks again!

Von: Sergey Kanzhelev [mailto:notifications@github.com]
Gesendet: Donnerstag, 13. April 2017 23:32
An: Microsoft/ApplicationInsights-SDK-Labs <ApplicationInsights-SDK-Labs@noreply.github.com>
Cc: Roethinger, Alexander <aroethinger@affili.net>; Mention <mention@noreply.github.com>
Betreff: Re: [Microsoft/ApplicationInsights-SDK-Labs] Issue with self-hosted WCF (#109)


Fix should be on myget
