### ISSUE TITLE
Is hosting app responsible for calling Flush() when ends?

### ISSUE THREAD

**Issue by jiberan** [Microsoft/ApplicationInsights-SDK-Labs#127]
Hi,
my WCF service is hosted in windows service but I'm not sure if I need to call client.Flush() when windows service stops to ensure that all data will be send.

Should I call it manually?

Thank you.
j.

**Comment by tomasr** [comment]
The default telemetry channels do buffer data, so you indeed might want to call `Flush()` before terminating.

**Comment by tomasr** [comment]
@jiberan You can just initialize one based on `TelemetryConfiguration.Active`, which will tie it to the configured telemetry channel, afaik.
