### ISSUE TITLE
ExceptionElemetry in ETW provider not working with AppInsights 2.1.0-beta4

### ISSUE THREAD

**Issue by bradtwurst** [Microsoft/ApplicationInsights-SDK-Labs#13]
When starting up a WCF service with AppInsights WCF included in the config, an error is reported that the ExecptionTelemetry event keyword 0x30 is invalid and that it must be a power of 2.

I downloaded the code, changed the 0x30 to 0x40, recompiled, and the modified version does not report the error.

https://github.com/Microsoft/ApplicationInsights-SDK-Labs/blob/master/WCF/Shared/Implementation/WcfEventSource.cs#L17

**Comment by abaranch** [comment]
Thank you for reporting the issue.
@tomasr , could you please take a look?

**Comment by tomasr** [comment]
@abaranch Yes, will send a pull request later today with the proper fix after checking everything else is OK.

@bradtwurst Thanks for reporting!
