### ISSUE TITLE
Add NIC placeholder for custom performance counters

### ISSUE THREAD

**Issue by wijays** [Microsoft/ApplicationInsights-SDK-Labs#138]
Currently there are these placeholders:

```
??APP_WIN32_PROC??
??APP_W3SVC_PROC??
??APP_CLR_PROC??
```

I propose that something similar to `??APP_WIN32_NIC??` be introduced so that performance counters such as `\Network Interface(*)\Current Bandwidth` that require the NIC name can be used.

**Comment by SergeyKanzhelev** [comment]
These placeholders are used when extra mapping is required between THE CURRENT process and performance counters INSTANCE NAME. In case of network counters you can simply specify the NIC you want to collect data for.

If your request is to support wildcard in names of performance counters that mean collect ALL instances - please file an issue here: https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues
