### ISSUE TITLE
UserAgent Initializer overrides User.Id

### ISSUE THREAD

**Issue by rodpl** [Microsoft/ApplicationInsights-SDK-Labs#139]
https://github.com/Microsoft/ApplicationInsights-SDK-Labs/blob/fd09b8ef47aafd84208b0bf3b63a86cc1df6d2fb/WCF/Shared/UserAgentTelemetryInitializer.cs#L41

Here should be userContext.UserAgent = knownAgent

**Comment by tomasr** [comment]
Well, that's embarrassing. Thanks for reporting! Just pushed a test + fix for this.
