### ISSUE TITLE
Has this repo been abandoned ? Please communicate + myget issues

### ISSUE THREAD

**Issue by Danthar** [Microsoft/ApplicationInsights-SDK-Labs#154]
- No commits / PR merged for over 8 months
- No answers of any kind on any of the issues regarding future planning and moving to nuget

It seems that this repo has been abandoned Microsoft style. Which means that nobody will confirm to the contrary, but Microsoft will just let it silently rot. Which is disheartening to be honest.

The reason why i came here:

We are having issues with the myget feed. https://developercommunity.visualstudio.com/content/problem/319369/visual-studio-2017-1581-nuget-hangs.html?childToView=361210#comment-361210

It is causing all kinds of problems with the nuget package manager. Because the feed is so slow, nuget hangs for extended periods of time, in our case often more then 1 hour.

So thing is. If microsoft is not going to spend alot more time on the WCF integration. Please communicate this. And would you guys consider simply brandishing the current WCF integration as a 'release' warts and all. And moving it off myget and into nuget. ...

Regarding the current state of the integration. Sure some things are missing. And there are some issues. But its very usable. Granted, this is from an outsiders point of view. Blissfully unaware of whatever standard MS holds in this regard.

Finishing off i wanted to end this post with: Please communicate with the community. Let us know whats happening. Because anyone coming here will now be seeing a Beta integration, with over 8 months of inactivity. With no idea what to expect in the future.

**Comment by Danthar** [comment]
And even if this integration has been deemed 'good enough'. Then please communicate this with the community! And release a new version of the integration that reflects this.

**Comment by SergeyKanzhelev** [comment]
Is the only issue to have WCF package publish on nuget?

This repo was created for experiments. When we experiment we are coming back =). So far we have very minor interest in WCF monitoring. I think we can lose our stands and publish it is this is critical

**Comment by Danthar** [comment]
I didn't realize that the labs are your experimental area. Looking at the readme, its like the first line in there :P totally missed that.

So yeah, myget feeds are continuing to cause problems when performing package updates on projects with many package dependencies (especially older style csproj's). So if you guys would consider moving to nuget. That would help us out.

**Comment by haldiggs** [comment]
we love WCF integration. I would have to forget using Insights and find something else if not for the WCF integration piece.

**Comment by rokern002** [comment]
it would be great if the package will be moved to nuget, even if its a pre version. AI is a powerfull tool and there are alot of wcf projects where the maintainability can be improved just by attaching AI
