### ISSUE TITLE
Getting error in event source initialization in AggregateMetrics project

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-SDK-Labs#20]
ERROR: Exception in Command Processing for EventSource Microsoft-ApplicationInsights-Extensibility-AggregateMetrics: Use of undefined keyword value 0x10 for event ModuleInitializationStarted.

Have no idea why it happens. It doesn't affect execution, but need to look into it.

**Comment by abaranch** [comment]
You may want to try to make nested Keywords class public. Also consider adding reference to Microsoft.Diagnostics.Tracing.EventRegister that adds a target so that such issues are caught during build time.

**Comment by SergeyKanzhelev** [comment]
thanks! 🎉
