### ISSUE TITLE
Works with Live Stream?

### ISSUE THREAD

**Issue by brettjacobson** [Microsoft/ApplicationInsights-SDK-Labs#22]
Will this package work with/support the latest Live Stream features of AppInsights 2.1?  
I cannot determine if those features are a part of the Web SDK (which this "replaces") or not.

**Comment by tomasr** [comment]
Are you referring specifically to the WCF part? or something else?

**Comment by SergeyKanzhelev** [comment]
Live Stream metrics are part of Performance Counter package that is a dependency for WCF one. So it's suppose to be working.

**Comment by SergeyKanzhelev** [comment]
Please re-open if Live Stream is not working when you are using WCF package
