### ISSUE TITLE
 WCF Telemetry Module could not load Microsoft.ApplicationInsights, Version=2.1.0.0

### ISSUE THREAD

**Issue by jiberan** [Microsoft/ApplicationInsights-SDK-Labs#23]
When WCF service is started it will show error `Could not load file or assembly 'Microsoft.ApplicationInsights, Version=2.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.`

Using  latest version of ApplicationInsights.Wcf - 0.26.0-build00473. and .net 4.0

Can you check on that?
Thanks.

**Comment by tomasr** [comment]
Thanks for the report, @jiberan. Can you clarify something?
You mention that the error is happening on .NET 4.0... is this just a .NET 4.0 service running on a machine with *only* .NET 4.0 installed, or does the machine have 4.5.X? or higher?
Do you see the same thing happening for a project built for .NET 4.5?

**Comment by jiberan** [comment]
It is Windows 10 with .net 4.6 and project with 4.0 target. Just tried and problem is the same with 4.5.2. Looks like .net version is irrelevant.

You can just create new WCF Service Application, install Package "Microsoft.ApplicationInsights.Wcf" -Pre and run application. It will immediately crash.

**Comment by tomasr** [comment]
Figured it out; the NuGet package is pulling the wrong version of the Microsoft.ApplicationInsights.* packages (2.0.0 and not 2.1.0). I'm doing a pull request to fix it in a moment, but in the meantime you can work around it by manually updating the Microsoft.ApplicationInsights.WindowsServer NuGet package to the latest stable version (2.1.0).

**Comment by jiberan** [comment]
it is working now. Thanks :+1:

**Comment by ACsharp** [comment]
I have the same issue. Project targeting .NET 4.0 and including Microsoft.ApplicationInsights.WindowsServer 2.2.0.

**Comment by tomasr** [comment]
@ACsharp Can you clarify a bit more what problem you're having? I just did a quick test with the current package in MyGet and not seeing any issues....

**Comment by ACsharp** [comment]
@tomasr interestingly this issue seems to be environment-dependent.
It works on VS 2015 on Windows 10. It does not work on VS 2013 on Windows 7

Repro steps:
- Create a new WCF app targeting .Net 4.0
- Add Microsoft.ApplicationInsights.Wcf via Nuget (last version 0.26.0-build49415)
- Run the application
> Could not load file or assembly 'Microsoft.AI.Wcf' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)

**Comment by tomasr** [comment]
@SergeyKanzhelev Any idea where this might be coming from?

**Comment by SergeyKanzhelev** [comment]
Hm, it seems that wcf wasn't signed for `net40`. As a workaround - migrate your projects to `net45+`. I'll look into it

```
PS> sn -vf C:\temp\WcfService2\packages\Microsoft.ApplicationInsights.Wcf.0.26.0-build49415\lib\net40\Microsoft.AI.Wcf.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.33440
Copyright (c) Microsoft Corporation.  All rights reserved.

C:\temp\WcfService2\packages\Microsoft.ApplicationInsights.Wcf.0.26.0-build49415\lib\net40\Microsoft.AI.Wcf.dll is a delay-signed or test-signed assembly


PS> sn -vf C:\temp\WcfService2\packages\Microsoft.ApplicationInsights.Wcf.0.26.0-build49415\lib\net45\Microsoft.AI.Wcf.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.33440
Copyright (c) Microsoft Corporation.  All rights reserved.

Assembly 'C:\temp\WcfService2\packages\Microsoft.ApplicationInsights.Wcf.0.26.0-build49415\lib\net45\Microsoft.AI.Wcf.dll' is valid
```

**Comment by SergeyKanzhelev** [comment]
Should be fixed in `Microsoft.ApplicationInsights.Wcf.0.26.0-build52563`

**Comment by ACsharp** [comment]
It works now. Thank you, @SergeyKanzhelev for the quick and effective fix.
