### ISSUE TITLE
[AzureWeAppCounters] cleanup for Mateo

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-SDK-Labs#41]
1. File names should be the same as class names
2. Only public class should be `PerformanceCollectorModule` (and obviously `PerformanceCounterCollectionRequest` as it's public contract) - everything else internal. Move internal classes into `Implementation` folder
3. Populate `Counters` collection with the default counters in constructor
4. Rename `FlexiblePerformanceCounterGauge` to `PerformanceCounterFromJsonGauge`
5. Initialize `PerformanceCounterFromJsonGauge` with both - name of the counter and the name of the environment variable (one of `AzureWebApEnvironmentVariables`)
6. Rename `ICacheHelper` to 'ICachedEnvironmentVariableAccess`
7. Implement alternative implementation for unit tests that doesn't require access to `remoteenvironmentvariables.azurewebsites.net/`
9. Enable StyleCop for the project and fix StyleCop issues

**Comment by SergeyKanzhelev** [comment]
@mateoatr - this is for you

**Comment by SergeyKanzhelev** [comment]
@mateoatr - can you please comment which items still left to do?

**Comment by mateoatr** [comment]
Only items left are 5 and 7.

**Comment by mateoatr** [comment]
This is completed.
