### ISSUE TITLE
Unable to Restore or Install Stable version - 0.25.0 of  Microsoft.ApplicationInsights.Wcf package 

### ISSUE THREAD

**Issue by manums** [Microsoft/ApplicationInsights-SDK-Labs#49]
We had 0.25.0 stable version of ApplicationInsights.Wcf package installed in our solution. From sometime, Restoring nuget started failing. I tried the solution suggested in i.e. by updating Nuget.config -http://docs.myget.org/docs/how-to/package-not-found-during-package-restore. However, restoring or installing nuget failing cos there is no such stable version available.

I have noticed that this stable version is not available anymore, I only see Prerelease versions in https://www.myget.org/F/applicationinsights-sdk-labs/. 

I wanted to know  how do i go back to stable version.

**Comment by tomasr** [comment]
@manums There was a problem with one of the builds published that reverted back to the wrong version number and overwrote some important changes. Could be that was indeed the build you were referring to, though I do not believe we've marked any build as stable explicitly.

@SergeyKanzhelev do you know more about this?

Overall would recommend to go with the latest version, as it contains a few improvements and bug fixes.

**Comment by SergeyKanzhelev** [comment]
Yes, we marked one package as stable by mistake. @manums - do you have a requirement to use a stable version? If you don't - please follow @tomasr recommendation and use the latest.

**Comment by manums** [comment]
@SergeyKanzhelev  @tomasr Thanks for the replies, I could update it to latest but the code has already gone live.  I will have to wait for next release to make these updates. 

Our application is business critical and hence process mandates to use only "Stable" versions of external libraries and packages. We created POCs before updating to 0.25.0 which was marked as stable. 

When can we expect a stable version to be released? Also can you list any known defects with 0.25.0 version which I should be aware of?

**Comment by SergeyKanzhelev** [comment]
Like or leave a comment in this issue: https://github.com/Microsoft/ApplicationInsights-SDK-Labs/issues/5 please
