### ISSUE TITLE
[AzureWeAppCounters] CPU counters seems to be incorrect

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-SDK-Labs#52]
There are two CPU counters:

\Processor(_Total)\% Processor Time
\Process(??APP_WIN32_PROC??)\% Processor Time

Looking in the code it seems we only support the first one: https://github.com/Microsoft/ApplicationInsights-SDK-Labs/blob/azureWebAppCounters/AggregateMetrics/AggregateMetrics/AzureWebApp/Implementation/CounterFactory.cs#L40 However I believe it may be incorrect and values we get from JSON are for the current process, not for the entire sandbox.

Please validate which one we can actually collect for Azure

**Comment by mateoatr** [comment]
@SergeyKanzhelev Yes, you're right, right now we're only getting values for the current process. I'm changing it.
