### ISSUE TITLE
ArgumentNullException on Telemetry Initialize

### ISSUE THREAD

**Issue by ranjitkrishnan** [Microsoft/ApplicationInsights-SDK-Labs#64]
I am using AppInsights WCF  in my service. I am noticing exceptions getting thrown from AppInsights while initializing  telemetry. Exception happens in the IsClientSideContext method where context is going as null.

The error happens for the following

- OperationNameTelemetryInitializer
- OperationCorrelationTelemetryInitializer
- UserTelemetryInitializer
- UserAgentTelemetryInitializer
- ClientIpTelemetryInitializer

Application Insights WCF Version : 0.26.0.16866

Can you please help me with this issue

Please find the StackTrace below for OperationNameTelemetryInitializer.

[msg=Log Error];[msg=Exception while initializing Microsoft.ApplicationInsights.Wcf.OperationNameTelemetryInitializer, exception message - System.ArgumentNullException: Value cannot be null.
Parameter name: context
   at Microsoft.ApplicationInsights.Wcf.OperationContextExtensions.IsClientSideContext(OperationContext context) in D:\A\_work\35\s\WCF\Shared\OperationContextExtensions.cs:line 43
   at Microsoft.ApplicationInsights.Wcf.Implementation.WcfOperationContext.GetContext() in D:\A\_work\35\s\WCF\Shared\Implementation\WcfOperationContext.cs:line 108
   at Microsoft.ApplicationInsights.Wcf.Implementation.WcfOperationContext.get_Current() in D:\A\_work\35\s\WCF\Shared\Implementation\WcfOperationContext.cs:line 44
   at Microsoft.ApplicationInsights.Wcf.WcfTelemetryInitializer.Initialize(ITelemetry telemetry) in D:\A\_work\35\s\WCF\Shared\WcfTelemetryInitializer.cs:line 28
   at Microsoft.ApplicationInsights.TelemetryClient.Initialize(ITelemetry telemetry)]

**Comment by tomasr** [comment]
@ranjitkrishnan Thanks for the bug report. Can you tell me what your code looks like? How are you using the library?

Are you manually instantiating a TelemetryClient instance on a thread that is not part of WCF?

**Comment by ranjitkrishnan** [comment]
Please find the steps in which i have configured my service.

- Added the nuget package Microsoft.Ai.Wcf from the AppInsights labs. 
- In the Application_Start of Global.asax, i am initializing the instrumentation key from appsetting instead of the ApplicationInsights.config. This is because, we will have different resources for dev, qa, staging and production and wanted to keep the instrumentation keys in the web.config so that ApplicationInsights.config can be kept unchanged in different environments

So global.asax, has the following line

TelemetryConfiguration.Active.InstrumentationKey = WebConfigurationManager.AppSettings["iKey"];

- Created a service behavior for tracking exceptions which extends the HandleError method like this.

bool IErrorHandler.HandleError(Exception error)
        {
            // Application Insight Logging
            var telemetry = new ExceptionTelemetry(error);

            telemetryClient.TrackException(telemetry);
            return false;
        }

We dont have any other custom coding on ApplicationInsights at this point.

**Comment by tomasr** [comment]
Couple of things:

You don't need to manually set the instrumentation key in `Application_Start`. Adding it in Web.Config is already supported if you're injecting the attribute through configuration, like this:

```XML
<serviceBehaviors>
   <behavior name="myBehavior">
      <serviceTelemetry instrumentationKey="<key_here>" />
   </behavior>
<serviceBehaviors>
```
You also don't need to inject your own `IErrorHandler` implementation to log exceptions, as this is already done automatically by the library; or is there any reason why it's not working for you?

Also just added a pull request to add a missing null reference check which should work around your specific exception.

**Comment by ranjitkrishnan** [comment]
Thanks Tomas. I have removed the code in ApplicationStart and added the instrumentationkey in the behavior itself. It is working.

I have taken the code and built it locally and tested the fix you have provided. There is no exception afterwards.

When can i get this fix available in nuget ?
