### ISSUE TITLE
WCF limitation - actual?

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-SDK-Labs#89]
Hi @tomasr 

Is this [limitation](https://github.com/Microsoft/ApplicationInsights-SDK-Labs/blob/master/WCF/readme.md#current-limitations) is still actual:

>Tracking WCF services in a single application where you're already using the Web Applications SDK is not supported

I thought it is gone and can be removed from readme

**Comment by tomasr** [comment]
We can close this now as this is no longer a limitation
