### ISSUE TITLE
Does this also work with WCF Data Services?

### ISSUE THREAD

**Issue by ranveeraggarwal** [Microsoft/ApplicationInsights-SDK-Labs#91]
We have a WCF OData service and I tried to install Microsoft.ApplicationInsights.WCF in it. While, there were no errors, I couldn't see any tracking data.

Following the same steps on a vanilla WCF Service works for me.

So does this work on WCF Data Services by changing some configuration? If not, is there a similar package for the same?

**Comment by tomasr** [comment]
It should work, provided the `<serviceTelemetry/>` behavior is correctly configured on the service. I've tested it once, and it worked, though I'm not sure it provides the best possible experience and would be keen to improve it.

What specific telemetry would you like to see? How would you like operations to be reported? Any specific data you'd like to see included in Request events?

**Comment by ranveeraggarwal** [comment]
Currently, I don't need any custom events to be tracked, I just need my requests and server response time to be logged. 

I didn't make any change apart from the steps described in the README (i.e., install and add instrumentation key).

**Comment by tomasr** [comment]
Make sure you specified the `<InstrumentationKey>` element correctly in the ApplicationInsights.config file....

**Comment by ranveeraggarwal** [comment]
Is that all that's required to make it work? In that case, I'll see if there's any other problem. Thanks for your help :)

**Comment by tomasr** [comment]
Well, as I mentioned, it's either the Key being specified incorrectly, or the `<serviceTelemetry>` behavior is not in effect. The default NuGet package installation only adds the behavior to the unnamed `<serviceBehavior>` entry, but depending on how your service is configured, that might not be the right option. If you share your service config, we can help you ensure it is being used.

Alternatively, you could modify the code to add the `[ServiceTelemetry]` attribute to your service class; that will also do the trick.
