### ISSUE TITLE
Type 'Microsoft.ApplicationInsights.Wcf.Implementation.WcfOperationContext' in Assembly 'Microsoft.AI.Wcf, Version=0.26.0.60740, Culture=neutral, PublicKeyToken=31bf3856ad364e35' is not marked as serializable.

### ISSUE THREAD

**Issue by CanerPatir** [Microsoft/ApplicationInsights-SDK-Labs#92]
I get the following exception when using SqlServer.SMO libraries.  Type 'Microsoft.ApplicationInsights.Wcf.Implementation.WcfOperationContext' in Assembly 'Microsoft.AI.Wcf, Version=0.26.0.60740, Culture=neutral, PublicKeyToken=31bf3856ad364e35' is not marked as serializable.

**Comment by tomasr** [comment]
Could you tell me what your code is doing with the SMO libraries? That might give a hint as what is going on.

I suspect the issue is that it's using a second AppDomain and trying to marshal the call context across them.

**Comment by tomasr** [comment]
@CanerPatir We've published version `0.26.1-build00103` of the package on MyGet with the changes. Could you test and see if it fixes the issue for you?

**Comment by CanerPatir** [comment]
Thank you, it looks working successfully anymore.
