### ISSUE TITLE
Builds broken in VS2017

### ISSUE THREAD

**Issue by tomasr** [Microsoft/ApplicationInsights-SDK-Labs#96]
Just ran into this: Opening the solutions in VS2017 is currently broken; VS will think that the `<IntermediateOutputPath>` is not set, causing it to try to modify the project files on open. Builds are broken with the matching MSBuild because `<BaseIntermediatePath>` does not get set correctly and ends up pointing somewhere under Program Files.

The cause of the issue is a change in MSBuild: https://github.com/Microsoft/msbuild/issues/1525

This is triggered by line 70 in Globals.props:

```XML
        <BaseIntermediateOutputPath Condition="'$(BaseIntermediateOutputPath)' == '' ">$(EnlistmentRoot)\..\obj</BaseIntermediateOutputPath>
```

Specifically, the condition returns false (since it now has a value by default), so all the intermediate path settings after that yield the wrong result.

Seems like removing the condition would be the simplest fix, as I can't see a case where to avoid setting it always.

Thoughts?

**Comment by SergeyKanzhelev** [comment]
Installing an RTM of VS 2017 to try it out...

**Comment by SergeyKanzhelev** [comment]
@tomasr if you'd have time - please try to apply similar change: https://github.com/Microsoft/ApplicationInsights-dotnet/pull/466#pullrequestreview-26937657

Not sure it will fix this problem, but it will help with Stylecop

**Comment by tomasr** [comment]
@SergeyKanzhelev Yes, that fixes it. And figured out why StyleCop wasn't kicking in: I never added the Settings.StyleCop file and the StyleCop.MSBuild nuget *facepalm*. Now I've got a lovely 6200+ warnings :/

**Comment by SergeyKanzhelev** [comment]
You can exclude all existing files from stylecop analysis so only new files will need to be fixed. Later we can uncomment files one by one.

**Comment by tomasr** [comment]
I've now fixed all of the issues in the existing source (I think), but here's a question... how are you dealing with the old StyleCop parser throwing SA0102 errors on newish C# features? Seems this is expected, so wonder if you're just avoiding the use of such constructs for now?

Seems like the recommended alternative is to move to https://github.com/DotNetAnalyzers/StyleCopAnalyzers.

**Comment by SergeyKanzhelev** [comment]
I think we will be moving to analyzer where possible. But the latest stylecop should support those language constructions... Can you please try to update the `StyleCop.MSBuild` package to the latest?

**Comment by tomasr** [comment]
@SergeyKanzhelev Yep, already on latest. Specifically seems to dislike using `?? throw` for null-check + assignment, as in:

``` C#
this.telemetryClient = client ?? throw new ArgumentNullException(nameof(client));
```
